# Generated by Django 5.2.17 on 2026-08-15 18:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AFP',
                'verbose_name_plural': 'AFP',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InstitucionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('FONASA', 'FONASA'), ('ISAPRE', 'ISAPRE')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'institución de salud',
                'verbose_name_plural': 'instituciones de salud',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EXPORTADO', 'Exportado')], default='ABIERTO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'período de liquidación',
                'verbose_name_plural': 'períodos de liquidación',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_medida', models.CharField(choices=[('DIAS', 'Días'), ('MINUTOS', 'Minutos'), ('PESOS', 'Pesos'), ('REGISTRO', 'Registro')], max_length=15)),
                ('naturaleza', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('HABER', 'Haber'), ('DESCUENTO', 'Descuento'), ('INFORMATIVO', 'Informativo')], max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de novedad',
                'verbose_name_plural': 'tipos de novedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('CORRIENTE', 'Cuenta corriente'), ('VISTA', 'Cuenta vista'), ('AHORRO', 'Cuenta de ahorro'), ('CUENTA_RUT', 'Cuenta RUT'), ('OTRA', 'Otra')], max_length=20)),
                ('cargas_familiares', models.PositiveSmallIntegerField(default=0)),
                ('seguro_cesantia', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='novedades.afp')),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='novedades.banco')),
                ('institucion_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='novedades.institucionsalud')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colaboradores', to='novedades.sucursal')),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(choices=[('XLSX', 'Excel'), ('CSV', 'CSV')], max_length=10)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('cantidad_registros', models.PositiveIntegerField(default=0)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones', to='novedades.periodoliquidacion')),
            ],
            options={
                'verbose_name': 'exportación',
                'verbose_name_plural': 'exportaciones',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.AddField(
            model_name='periodoliquidacion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_liquidacion', to='novedades.sucursal'),
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADA', 'Validada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.colaborador')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_creadas', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_validadas', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.periodoliquidacion')),
                ('tipo_novedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.tiponovedad')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'novedades',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo fijo'), ('OTRO', 'Otro')], max_length=20)),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('cargo', models.CharField(max_length=100)),
                ('centro_costo', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='novedades.colaborador')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
                'ordering': ['-fecha_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('colaborador',), name='unico_contrato_activo_colaborador'), models.CheckConstraint(condition=models.Q(('fecha_termino__isnull', True), ('fecha_termino__gte', models.F('fecha_inicio')), _connector='OR'), name='contrato_fecha_termino_valida'), models.CheckConstraint(condition=models.Q(('sueldo_base__gt', 0)), name='contrato_sueldo_base_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodoliquidacion',
            constraint=models.UniqueConstraint(fields=('sucursal', 'anio', 'mes'), name='periodo_unico_sucursal_anio_mes'),
        ),
        migrations.AddConstraint(
            model_name='periodoliquidacion',
            constraint=models.CheckConstraint(condition=models.Q(('anio__gte', 2000), ('anio__lte', 2100)), name='periodo_anio_valido'),
        ),
        migrations.AddConstraint(
            model_name='periodoliquidacion',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='periodo_mes_valido'),
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__isnull', True), ('fecha_termino__isnull', True), ('fecha_termino__gte', models.F('fecha_inicio')), _connector='OR'), name='novedad_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__isnull', True), ('cantidad__gte', 0), _connector='OR'), name='novedad_cantidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='novedad',
            constraint=models.CheckConstraint(condition=models.Q(('monto__isnull', True), ('monto__gte', 0), _connector='OR'), name='novedad_monto_no_negativo'),
        ),
    ]
