# Generated by Django 5.2.17 on 2026-09-15 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedad_anulado_en_novedad_anulado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Si se asigna una sucursal, el usuario operará exclusivamente en dicha sucursal. Dejar en blanco para usuarios con acceso global (Administrador general o Contabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='novedades.sucursal', verbose_name='sucursal asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
            },
        ),
    ]
